- name: Orthodontic Treatment
  description: Teeth are not straight? Get your braces and have a perfect smile.
  icon: flaticon-tooth-with-braces
- name: Teeth Whitening
  description: Have yellow teeth? Get a brighter and healthier smile you've been wanting.
  icon: flaticon-tooth-1
- name: Teeth Cleaning
  description: Clean your teeth now with affordable price.
  icon: flaticon-bacteria
- name: Tooth Extraction
  description: Have a loose tooth? Extract your tooth with our clinic.
  icon: flaticon-dental-care
- name: Dental Surgery
  description: Any dental surgery you need at your service.
  icon: flaticon-dentist
- name: Dental Fillings
  description: Have yellow teeth? Get a brighter and healthier smile you've been wanting.
  icon: flaticon-tooth
- name: Root Canal
  description: Treat your root canal affordably and painlessly.
  icon: flaticon-dental-care-1
- name: Dentures
  description: Have missing tooth? Replace it with our dentures!
  icon: flaticon-dental-care
